### ISSUE TITLE
Feature Request: Progress % when downloading/updating Server

### ISSUE THREAD

**Issue by OS17279** [micah686/SatisfactoryServerGUI#2]
Per title, this would be a welcome addition

**Comment by micah686** [comment]
Unfortunately, due to the fact that SteamCMD isn't writing to the standard output, it's not easy to capture (see [link](https://github.com/ValveSoftware/Source-1-Games/issues/1684#issuecomment-280846576)).
However, you can view the progress by going to Logs, selecting SteamCMD, and watching the progress there.
